import { BetiOptions, BetiPreset } from '../types';

export const PRESETS: Record<BetiPreset, BetiOptions> = {
  card: {
    mask: '9999 9999 9999 9999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'luhn',
  },
  expiry: {
    mask: '99/99',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'expiry',
  },
  cvv: {
    mask: '999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
  },
  tckn: {
    mask: '99999999999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'tckn',
  },
  phone: {
    mask: '(999) 999 99 99',
    allowedChars: /[0-9]/,
    inputMode: 'tel',
    type: 'tel',
  },
  email: {
    allowedChars: /[a-zA-Z0-9@._+-]/,
    inputMode: 'email',
    type: 'email',
    validate: true,
    validator: 'email',
  },
  url: {
    allowedChars: /[a-zA-Z0-9@:%._\+~#=/?&-]/,
    inputMode: 'url',
    type: 'url',
    validate: true,
    validator: 'url',
  },
  username: {
    usernameFormat: true,
    inputMode: 'text',
    type: 'text',
  },
  alpha: {
    allowedChars: /[a-zA-ZçÇğĞıİöÖşŞüÜ ]/,
    inputMode: 'text',
    type: 'text',
    alphaFormat: true,
  },
  password: {
    type: 'password',
  },
  text: {
    type: 'text',
  },
  currency: {
    currency: {
      precision: 2,
      decimalSeparator: ',',
      thousandSeparator: '.',
      symbol: '',
      symbolPosition: 'prefix',
    },
    allowedChars: /[0-9]/,
    inputMode: 'decimal',
    type: 'text',
  },
  iban: {
    mask: '99 9999 9999 9999 9999 9999 99',
    displayPrefix: 'TR',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'iban',
  },
  numeric: {
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
  },
  date: {
    mask: '99/99/9999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'date',
    dateFormat: 'DMY',
  },
  taxNumber: {
    mask: '9999999999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
    validate: true,
    validator: 'vkn',
  },
  zipCode: {
    mask: '99999',
    allowedChars: /[0-9]/,
    inputMode: 'numeric',
    type: 'tel',
  },
};
